export default dataFile = {
  id: "evt_1NVpLPB8RK1QdFnYoldCY6iD",
  object: "event",
  api_version: "2022-11-15",
  created: 1689830646,
  data: {
    object: {
      id: "sub_1NVpLNB8RK1QdFnYFsN92lTS",
      object: "subscription",
      application: null,
      application_fee_percent: null,
      automatic_tax: {
        enabled: false,
      },
      billing_cycle_anchor: 1689830645,
      billing_thresholds: null,
      cancel_at: null,
      cancel_at_period_end: false,
      canceled_at: null,
      cancellation_details: {
        comment: null,
        feedback: null,
        reason: null,
      },
      collection_method: "charge_automatically",
      created: 1689830645,
      currency: "usd",
      current_period_end: 1692509045,
      current_period_start: 1689830645,
      customer: "cus_OIQBiGFvmFNlx1",
      days_until_due: null,
      default_payment_method: null,
      default_source: null,
      default_tax_rates: [],
      description: null,
      discount: null,
      ended_at: null,
      items: {
        object: "list",
        data: [
          {
            id: "si_OIQBqgTan013Ai",
            object: "subscription_item",
            billing_thresholds: null,
            created: 1689830646,
            metadata: {},
            plan: {
              id: "price_1NQ2iBB8RK1QdFnYWbG2BHuC",
              object: "plan",
              active: true,
              aggregate_usage: null,
              amount: 10000,
              amount_decimal: "10000",
              billing_scheme: "per_unit",
              created: 1688452063,
              currency: "usd",
              interval: "month",
              interval_count: 1,
              livemode: false,
              metadata: {},
              nickname: null,
              product: "prod_OCRbojGZUBhCgH",
              tiers_mode: null,
              transform_usage: null,
              trial_period_days: null,
              usage_type: "licensed",
            },
            price: {
              id: "price_1NQ2iBB8RK1QdFnYWbG2BHuC",
              object: "price",
              active: true,
              billing_scheme: "per_unit",
              created: 1688452063,
              currency: "usd",
              custom_unit_amount: null,
              livemode: false,
              lookup_key: null,
              metadata: {},
              nickname: null,
              product: "prod_OCRbojGZUBhCgH",
              recurring: {
                aggregate_usage: null,
                interval: "month",
                interval_count: 1,
                trial_period_days: null,
                usage_type: "licensed",
              },
              tax_behavior: "exclusive",
              tiers_mode: null,
              transform_quantity: null,
              type: "recurring",
              unit_amount: 10000,
              unit_amount_decimal: "10000",
            },
            quantity: 1,
            subscription: "sub_1NVpLNB8RK1QdFnYFsN92lTS",
            tax_rates: [],
          },
        ],
        has_more: false,
        total_count: 1,
        url: "/v1/subscription_items?subscription=sub_1NVpLNB8RK1QdFnYFsN92lTS",
      },
      latest_invoice: "in_1NVpLNB8RK1QdFnYrNvlemvo",
      livemode: false,
      metadata: {},
      next_pending_invoice_item_invoice: null,
      on_behalf_of: null,
      pause_collection: null,
      payment_settings: {
        payment_method_options: null,
        payment_method_types: null,
        save_default_payment_method: "off",
      },
      pending_invoice_item_interval: null,
      pending_setup_intent: null,
      pending_update: null,
      plan: {
        id: "price_1NQ2iBB8RK1QdFnYWbG2BHuC",
        object: "plan",
        active: true,
        aggregate_usage: null,
        amount: 10000,
        amount_decimal: "10000",
        billing_scheme: "per_unit",
        created: 1688452063,
        currency: "usd",
        interval: "month",
        interval_count: 1,
        livemode: false,
        metadata: {},
        nickname: null,
        product: "prod_OCRbojGZUBhCgH",
        tiers_mode: null,
        transform_usage: null,
        trial_period_days: null,
        usage_type: "licensed",
      },
      quantity: 1,
      schedule: null,
      start_date: 1689830645,
      status: "incomplete",
      test_clock: null,
      transfer_data: null,
      trial_end: null,
      trial_settings: {
        end_behavior: {
          missing_payment_method: "create_invoice",
        },
      },
      trial_start: null,
    },
  },
  livemode: false,
  pending_webhooks: 1,
  request: {
    id: "req_H4cBmGrpBgwJu2",
    idempotency_key: "ad96bd0a-7681-42de-b404-c7a906f39718",
  },
  type: "customer.subscription.created",
};
